# Generated by Django 4.0.1 on 2023-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_is_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
