# Generated by Django 4.0.1 on 2022-06-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_attachemt_author_coupon_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachemt',
            new_name='Attachment',
        ),
    ]
