# Generated by Django 4.0.1 on 2022-06-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_attachemt_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercheckoutverify',
            name='unavailable_products',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
