# Generated by Django 4.0.1 on 2022-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
