# Generated by Django 4.0.1 on 2022-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, to='store.Address'),
        ),
    ]
