# Generated by Django 4.0.1 on 2022-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
