# Generated by Django 4.0.1 on 2022-06-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_address_title_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
