# Generated by Django 4.0.1 on 2022-06-14 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_amount_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerId',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
