# Generated by Django 4.0.1 on 2022-06-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='store.order'),
        ),
    ]
