# Generated by Django 4.0.1 on 2022-06-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_useraddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='typeid',
        ),
    ]
