# Generated by Django 4.0.1 on 2022-06-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='order',
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='store.order'),
        ),
    ]
