# Generated by Django 4.0.1 on 2022-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_address_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='children',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logistics_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sales_tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
