# Generated by Django 4.0.1 on 2022-06-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_order_address_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercheckoutverify',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='ordercheckoutverify',
            name='unavailable_products',
        ),
        migrations.RemoveField(
            model_name='ordercheckoutverify',
            name='wallet_amount',
        ),
        migrations.RemoveField(
            model_name='ordercheckoutverify',
            name='wallet_currency',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
