# Generated by Django 4.0.1 on 2022-06-15 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_ordercheckoutverify_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='children',
            field=models.ManyToManyField(to='store.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercheckoutverify',
            name='shipping_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercheckoutverify',
            name='unavailable_products',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.AddField(
            model_name='ordercheckoutverify',
            name='wallet_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercheckoutverify',
            name='wallet_currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='test name', max_length=200),
            preserve_default=False,
        ),
    ]
