# Generated by Django 4.0.1 on 2022-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_cardinput_connectproductorderpivot_orderproductpivot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectproductorderpivot',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='connectproductorderpivot',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
