# Generated by Django 4.0.1 on 2022-06-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_connectproductorderpivot_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedCheckoutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tax', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
                ('wallet_currency', models.IntegerField(blank=True, null=True)),
                ('wallet_amount', models.IntegerField(blank=True, null=True)),
                ('unavailable_products', models.ManyToManyField(blank=True, to='store.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderCheckoutVerify',
        ),
    ]
