# Generated by Django 4.0.1 on 2022-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_verifiedcheckoutdata_delete_ordercheckoutverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
