# Generated by Django 4.0.1 on 2022-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='V6oaBCmPIU<built-in function id>', max_length=100),
        ),
    ]
