# Generated by Django 4.0.1 on 2022-09-28 14:21

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default=store.models.random_string, max_length=15),
        ),
    ]
