# Generated by Django 4.0.1 on 2022-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_orderproductpivot_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesettings',
            name='layoutType',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('standard', 'Standard'), ('compact', 'Compact'), ('minimal', 'Minimal')], default='classic', max_length=20),
        ),
    ]
