# Generated by Django 4.0.1 on 2022-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_typesettings_layouttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='promotional_sliders',
            field=models.ManyToManyField(blank=True, to='store.PromotionalSliders'),
        ),
    ]
