# Generated by Django 4.0.1 on 2022-12-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_types_promotional_sliders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
    ]
